# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Publications', path: 'menu', url: 'publications.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/ilopezgp'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/ilopezgo/'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Ignacio_Lopez-Gomez'}
- {icon: 'envelope', link: 'mailto:ilopezgo@caltech.edu'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
